// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-cbaMeTW49MCsli8cCyyyV-q_DjH0jI',
    appId: '1:1058278723905:web:60da5f2ae30f964b57d1c0',
    messagingSenderId: '1058278723905',
    projectId: 'coach-hub-11',
    authDomain: 'coach-hub-11.firebaseapp.com',
    storageBucket: 'coach-hub-11.firebasestorage.app',
    measurementId: 'G-1E3RZWQP4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpbU4Xqj43RTLL9892wmIvW6pRAqTx9w',
    appId: '1:1058278723905:android:ae3b3d0f575b368157d1c0',
    messagingSenderId: '1058278723905',
    projectId: 'coach-hub-11',
    storageBucket: 'coach-hub-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBvzu2PbB7asSEyxZVyu7uuSgtywILqI',
    appId: '1:1058278723905:ios:3d25466d0d502c4e57d1c0',
    messagingSenderId: '1058278723905',
    projectId: 'coach-hub-11',
    storageBucket: 'coach-hub-11.firebasestorage.app',
    iosClientId: '1058278723905-dm5mpou823pb9a737n33c7ltrlm4atsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.s760126Team01FlutterFirebaseCoachhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX-cbaMeTW49MCsli8cCyyyV-q_DjH0jI',
    appId: '1:1058278723905:web:60da5f2ae30f964b57d1c0',
    messagingSenderId: '1058278723905',
    projectId: 'coach-hub-11',
    authDomain: 'coach-hub-11.firebaseapp.com',
    storageBucket: 'coach-hub-11.firebasestorage.app',
    measurementId: 'G-1E3RZWQP4N',
  );

}